Repository PepperDash/Essentials, pull requests merged in 2020-05, with the labels that each got.

#149 fixes master.yml action
  .github/workflows/master.yml
Labels: CI/CD Pipeline request

#156 Add dmc 4kz hdo support
  essentials-framework/Essentials Core/PepperDashEssentialsBase/JoinMaps/JoinMapBase.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmChassisController.cs
  essentials-framework/Essentials DM/Essentials_DM/Essentials_DM.csproj
Labels: enhancement

#153 Puts GetJoinMapForDevice method back into JoinMapHelper
  essentials-framework/Essentials Core/PepperDashEssentialsBase/JoinMaps/JoinMapBase.cs
Labels: bug

#157 Fix DM-TX-4KZ-302-C Audio feedback and routing
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz302CController.cs
Labels: bug

#164 Add CEN-ODT-C-POE Support
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/CenOdtOccupancySensorBaseJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.csproj
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Essentials Devices Common.csproj
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Occupancy/CenOdtOccupancySensorBaseController.cs
Labels: enhancement

#163 Update PepperDash.Essentials.Core join maps to use JoinMapAdvanced
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/AirMediaControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/AppleTvJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/C2nRthsControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DigitalLoggerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmBladeChassisControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmChassisControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmRmcControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmTxControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmpsAudioOutputControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmpsRoutingControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/GenericLightingJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/GenericRelayControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/GlsOccupancySensorBaseJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/HdMdxxxCEControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/IDigitalInputJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/SetTopBoxControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/StatusSignControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/SystemMonitorJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Config/Comm and IR/GenericComm.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/C2nRts/C2nRthsController.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/Inputs/GenericDigitalInputDevice.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/Relay/GenericRelayDevice.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/StatusSign/StatusSignController.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Display/DisplayBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Lighting/LightingBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Monitoring/SystemMonitorController.cs
  essentials-framework/Essentials DM/Essentials_DM/AirMedia/AirMediaController.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmBladeChassisController.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmChassisController.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmpsAudioOutputController.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmpsRoutingController.cs
  essentials-framework/Essentials DM/Essentials_DM/DmLite/HdMdxxxCEController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcHelper.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTxHelpers.cs
  essentials-framework/Essentials DM/Essentials_DM/PepperDash_Essentials_DM.csproj
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Environment/Lutron/LutronQuantum.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Essentials Devices Common.csproj
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Occupancy/GlsOccupancySensorBaseController.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Power Controllers/Digitallogger.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/SetTopBox/IRSetTopBoxBase.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Streaming/AppleTV.cs
Labels: enhancement

#170 Added AddJoinMap to CenOdtOccupancySensorBaseController
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Occupancy/CenOdtOccupancySensorBaseController.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Occupancy/GlsOccupancySensorBaseController.cs
Labels: enhancement

#159 Adds new feedback type to link Dm-Tx input video sync to generic "inp…
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmTxControllerJoinMap.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx200Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx201CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx401CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4k100Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4k202CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4k302CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz302CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTxHelpers.cs
Labels: enhancement

#166 Update workflow to add Crestron dlls to output
  .github/scripts/ZipBuildOutput.ps1
  .github/workflows/master.yml
Labels: CI/CD Pipeline request

#160 Refactor DM RMC Classes
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Routing/RoutingPort.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmHdBaseTEndpointController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc100SController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc150SController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc200CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc200S2Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc200SController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4KScalerCController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4k100C1GController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4kScalerCDspController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4kZ100CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4kZScalerCController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcHelper.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcScalerCController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcScalerS2Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcScalerSController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcX100CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz302CController.cs
Labels: enhancement

#172 Add DM-TX-4KZ-100-C-1G support
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz100Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTxHelpers.cs
  essentials-framework/Essentials DM/Essentials_DM/PepperDash_Essentials_DM.csproj
Labels: enhancement

#173 Update DeviceManager to provide protections for multiple threads or reentrancy
  PepperDashEssentials/ControlSystem.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Devices/DeviceManager.cs
Labels: enhancement

#175 Fix DisplayControllerJoinMap Constructor
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DisplayControllerJoinMap.cs
Labels: bug

#179 Add IHasVideoMute for projector interoperability
  PepperDashEssentials/UI/EssentialsTouchpanelController.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Devices/IProjectorInterfaces.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.csproj
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Display/InputInterfaces.cs
Labels: enhancement

#185 Remove release creation for alpha and beta builds
  .github/workflows/docker.yml
Labels: CI/CD Pipeline request

#184 Remove release creation for alpha & beta builds
  .github/workflows/docker.yml
Labels: CI/CD Pipeline request

#187 HD-MDNxM-4K-E Switch Improvements
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/HdMdNxM4kEControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Devices/EssentialsDevice.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.csproj
  essentials-framework/Essentials DM/Essentials_DM/Chassis/HdMdNxM4kEBridgeableController.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/HdMdNxM4kEController.cs
  essentials-framework/Essentials DM/Essentials_DM/Config/HdMdNxM4kEPropertiesConfig.cs
  essentials-framework/Essentials DM/Essentials_DM/Config/InputPropertiesConfig.cs
  essentials-framework/Essentials DM/Essentials_DM/PepperDash_Essentials_DM.csproj
Labels: enhancement

#191 Update DM USB Routing to match SIMPL Windows
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmChassisControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/StatusSign/StatusSignController.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/JoinMaps/JoinMapBase.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmChassisController.cs
Labels: bug

#206 Improve Control Port Constructors
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Config/Comm and IR/IRPortHelper.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/Inputs/GenericDigitalInputDevice.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/Relay/GenericRelayDevice.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Devices/IrOutputPortController.cs
Labels: enhancement

#211 Added Description Attributes to Bridgeable Classes
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Config/Comm and IR/DELETE ComPortController.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/Inputs/GenericDigitalInputDevice.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Crestron IO/Relay/GenericRelayDevice.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Display/BasicIrDisplay.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.csproj
  essentials-framework/Essentials DM/Essentials_DM/AirMedia/AirMediaController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/DGEs/Dge100Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/DGEs/DmDge200CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc100SController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc150SController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc200CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc200S2Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc200SController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4KScalerCController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4k100C1GController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4kScalerCDspController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4kZ100CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmc4kZScalerCController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcScalerCController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcScalerS2Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcScalerSController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Receivers/DmRmcX100CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx200Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx201CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx201SController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx401CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4k100Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4k202CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4k302CController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz100Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz302CController.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Occupancy/CenOdtOccupancySensorBaseController.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Occupancy/GlsOccupancySensorBaseController.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Occupancy/GlsOdtOccupancySensorController.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/SetTopBox/IRSetTopBoxBase.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Streaming/AppleTV.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Streaming/Roku.cs
Labels: enhancement

#207 Added new interface IRoutingNumeric
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Routing/RoutingInterfaces.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmBladeChassisController.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmChassisController.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmpsRoutingController.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/HdMdNxM4kEBridgeableController.cs
Labels: enhancement

#214 Updated JoinMetadata to add Description property
  essentials-framework/Essentials Core/PepperDashEssentialsBase/JoinMaps/JoinMapBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Remotes/Hrxx0WirelessRemoteController.cs
Labels: enhancement

#216 Fix incorrect cast in GenericComm LinkToApi method
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Config/Comm and IR/GenericComm.cs
  essentials-framework/Essentials DM/Essentials_DM/PepperDash_Essentials_DM.csproj
Labels: bug

#217 Fix incorrect cast in GenericComm LinkToApi method
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Comm and IR/GenericComm.cs
  essentials-framework/Essentials DM/Essentials_DM/PepperDash_Essentials_DM.csproj
Labels: bug

#221 Change ReleaseAndMakeRoute to use IRoutingSinkNoSwitching instead of IRoutingInputs
  PepperDashEssentials/Room/Types/EssentialsDualDisplayRoom.cs
  PepperDashEssentials/Room/Types/EssentialsHuddleSpaceRoom.cs
  PepperDashEssentials/Room/Types/EssentialsHuddleVtc1Room.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Routing/IRoutingInputsExtensions.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Routing/RoutingInterfaces.cs
Labels: bug
