Repository PepperDash/Essentials, pull requests merged in 2021-01, with the labels that each got.

#540 Hotfix/dge devinfo issues
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/DGEs/Dge100Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz302CController.cs
Labels: bug

#543 Release/1.7.0
  IR Drivers/Comcast X1.ir
  IR Drivers/DirecTV H21.ir
  PepperDashEssentials/Bridges/JoinMaps/DmChassisControllerJoinMap.cs
  PepperDashEssentials/ControlSystem.cs
  PepperDashEssentials/PepperDashEssentials.csproj
  PepperDashEssentials/Room/Config/EssentialsRoomConfig.cs
  PepperDashEssentials/Room/Config/EssentialsTechRoomConfig.cs
  PepperDashEssentials/Room/Types/EssentialsTechRoom.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/BridgeBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/DmChassisControllerJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Comm and IR/ComPortController.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Comm and IR/CommFactory.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/DeviceTypeInterfaces/INumeric.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/DeviceTypeInterfaces/ITvPresetsProvider.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Display/DisplayBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Fusion/EssentialsHuddleSpaceFusionSystemControllerBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Global/Scheduler.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.csproj
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.nuspec
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Plugins/PluginLoader.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Presets/DevicePresets.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Presets/PresetChannel.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Room/Config/EssentialsRoomScheduledEventsConfig.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Room/Interfaces.cs
  essentials-framework/Essentials DM/Essentials_DM/Chassis/DmChassisController.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/DGEs/Dge100Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz302CController.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/SetTopBox/IRSetTopBoxBase.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/VideoCodec/CiscoCodec/CiscoSparkCodec.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/VideoCodec/ZoomRoom/ResponseObjects.cs
  packages.config
Labels: bug, enhancement

#544 Release/1.7.0
  IR Drivers/Comcast X1.ir
  IR Drivers/DirecTV H21.ir
  PepperDashEssentials/Room/Types/EssentialsTechRoom.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/BridgeBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.nuspec
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Presets/DevicePresets.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/DGEs/Dge100Controller.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTx4kz302CController.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/SetTopBox/IRSetTopBoxBase.cs
  packages.config
Labels: bug, enhancement

#546 fixes a bug where the system monitor bridge wasn't updating
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Monitoring/SystemMonitorController.cs
Labels: bug

#547 Feature/merge into dev
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Devices/DeviceManager.cs
Labels: bug

#557 Feature/add fusion joinmaps
  .gitignore
  PepperDashEssentials/ControlSystem.cs
  PepperDashEssentials/Fusion/EssentialsHuddleVtc1FusionController.cs
  PepperDashEssentials/Fusion/EssentialsTechRoomFusionSystemController.cs
  PepperDashEssentials/PepperDashEssentials.csproj
  PepperDashEssentials/Room/Config/EssentialsRoomConfig.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/AppleTvJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Config/BasicConfig.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Config/Essentials/ConfigReader.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Fusion/EssentialsHuddleSpaceFusionSystemControllerBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Fusion/EssentialsHuddleSpaceRoomFusionRoomJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/JoinMaps/JoinMapBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.csproj
  packages.config
Labels: enhancement

#558 Feature/add fusion joinmaps
  .gitignore
  PepperDashEssentials/ControlSystem.cs
  PepperDashEssentials/Fusion/EssentialsHuddleVtc1FusionController.cs
  PepperDashEssentials/Fusion/EssentialsTechRoomFusionSystemController.cs
  PepperDashEssentials/PepperDashEssentials.csproj
  PepperDashEssentials/Room/Config/EssentialsRoomConfig.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Bridges/JoinMaps/AppleTvJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Config/BasicConfig.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Config/Essentials/ConfigReader.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Fusion/EssentialsHuddleSpaceFusionSystemControllerBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Fusion/EssentialsHuddleSpaceRoomFusionRoomJoinMap.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/JoinMaps/JoinMapBase.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.csproj
  packages.config
Labels: enhancement

#556 Feature/add hdbasettx support
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTxHelpers.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/HDBaseTTxController.cs
  essentials-framework/Essentials DM/Essentials_DM/PepperDash_Essentials_DM.csproj
Labels: enhancement

#569 Updates to properly clear errors when there are none and set message …
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Monitoring/StatusMonitorCollection.cs
Labels: bug

#570 Hotfix/fusion error rollup
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Monitoring/StatusMonitorCollection.cs
Labels: bug

#572 Sets the queue size to 25
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Queues/GenericQueue.cs
Labels: enhancement

#568 Validate method now checks the parameter
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Queues/ComsMessage.cs
Labels: bug

#573 Release/1.7.3
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Devices/DeviceJsonApi.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Devices/DeviceManager.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Interfaces/ILogStrings.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Interfaces/ILogStringsWithLevel.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/PepperDash_Essentials_Core.csproj
  essentials-framework/Essentials Core/PepperDashEssentialsBase/Queues/GenericQueue.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/DmTxHelpers.cs
  essentials-framework/Essentials DM/Essentials_DM/Endpoints/Transmitters/HDBaseTTxController.cs
  essentials-framework/Essentials DM/Essentials_DM/PepperDash_Essentials_DM.csproj
  essentials-framework/Essentials Devices Common/Essentials Devices Common/Essentials Devices Common.csproj
Labels: bug, enhancement

#579 Implements ITvPresetsProvider on IrSetTopBoxBase
  essentials-framework/Essentials Core/PepperDashEssentialsBase/DeviceTypeInterfaces/ISetTopBoxControls.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/UI PageManagers/SetTopBoxThreePanelPageManager.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/UI PageManagers/SetTopBoxTwoPanelPageManager.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/SetTopBox/IRSetTopBoxBase.cs
Labels: enhancement

#580 Hotfix/ir set top box base must implement i tv presets provider
  essentials-framework/Essentials Core/PepperDashEssentialsBase/DeviceTypeInterfaces/ISetTopBoxControls.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/UI PageManagers/SetTopBoxThreePanelPageManager.cs
  essentials-framework/Essentials Core/PepperDashEssentialsBase/UI PageManagers/SetTopBoxTwoPanelPageManager.cs
  essentials-framework/Essentials Devices Common/Essentials Devices Common/SetTopBox/IRSetTopBoxBase.cs
Labels: enhancement
